---
title: "What's next?"
date: "2024-07-23T10:20"
categories: [advice]
---

A bunch of you have asked me what other econ-related classes you can take. There aren't any other PMAP-offered econ classes, though the econ department in the Andrew Young School has, like, a billion of them since that's their thing. Those classes will be incredibly math-heavy, though, so fair warning.

I teach three other related-ish classes that you might find interesting:

### Program Evaluation

I teach a class called [Evaluation Research (PMAP 8521)](https://evalsp24.classes.andrewheiss.com/) in the spring. It's a really fun and useful class (I've had students get jobs because of it!), and tbh I find it far more practical and intuitive than econ :). It's basically a class in econometrics, or econ-flavored statistics focused on causation.

In the class you'll learn all about causal inference, or how to legally claim causation with statistics. In your past classes you were always taught "correlation isn't causation," which is mostly true, except when it's not. In this class, you'll get to legitimately make causal claims. We'll cover fun tools like directed acyclic graphs (DAGs), randomized controlled trials, difference-in-differences analysis, regression discontinuity analysis, and instrumental variables. You'll also learn the statistical language R, which is free (which means you can keep using it after you graduate and not have to pay for really really expensive SPSS or Stata licenses). The R part is why former students have found jobs—tons of organizations are looking for R skills nowadays.

If you can interpret regression results and if you know what statistical significance means, you have the stats background for the class.

[You can see the website from the most recent version of the class](https://evalsp24.classes.andrewheiss.com/), and it's full of videos and interactive code tutorials and other resources.

### Comparative Public Administration

In the fall, I teach a class called [Comparative Public Administration (PMAP 8441)](https://compasp23.classes.andrewheiss.com/), which is just fancy academic speak for "how the public and nonprofit sectors work in different countries." If you have any interest in international politics or international NGOs, you'd enjoy it!

[You can see the website from last year's version of the class here](https://compasp23.classes.andrewheiss.com/).

### Data Visualization

My most populuar class isn't related to econ, or even public administration or policy specifically. It's [Data Visualization with R (PMAP 8551)](https://datavizs24.classes.andrewheiss.com/), where you learn to use R to make all sorts of really neat plots and graphics. It covers basic graphic design principles in addition to fancy things like text analysis, GIS, and interactive and animated graphics. [Here's the most recent version of the class](https://datavizs24.classes.andrewheiss.com/).

It's an incredibly fun and useful class and I'd love to see some of you there in the future!
