---
title: "Problem set 6 extra credit"
date: "2024-07-17T01:02"
categories: [course details]
---

In order to get the extra credit from problem set 6, 12 of you needed to write [the sentences in question 4](/assignment/06-problem-set.html#section-3). 

One of you wrote the sentence just once. A few of you didn’t do it and didn’t say anything. One of you didn’t do it and explicitly said something along the lines of “Nope! I normally always help out and contribute in situations like this, but not this time—I'm too tired!” This is delightful and happens in real world situations all the time—well played :)

Did enough of you write the sentences?

.

.

.

.

.

.

*Exactly* 12 of you did it. You barely squeaked by :) One of you—still catching up with the rest of problem set 6—even submitted *only* the sentences just to help contribute to the overall pool.

And those of you who didn’t contribute get to free ride on everyone’s work, just like we all do when watching PBS or listening to NPR.

Three cheers for public goods and collective action!
